version: '3.4'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '443:443'
    restart: always
    # depends_on:
      # - tor
      # - nostr
      # - uptime_kuma
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - /var/www/certbot:/var/www/certbot/:ro
      - /etc/letsencrypt/:/etc/nginx/ssl/:ro
      - ./nostr:/nostr:ro
    networks:
      - nginx
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot:latest
    restart: always
    volumes:
      - /var/www/certbot/:/var/www/certbot/:rw
      - /etc/letsencrypt/:/etc/letsencrypt/:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  # nostr:
  #   image: koalasat/satstralia-web-nostr:0.6
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - ./strfry/onion_urls.txt:/app/onion_urls.txt:ro
  #     - ./strfry/config/strfry.conf:/etc/strfry.conf:ro
  #     - ./strfry/db:/app/strfry-db:rw
  #   networks:
  #     - nginx
  # uptime_kuma:
  #   image: louislam/uptime-kuma
  #   restart: always
  #   ports:
  #     - 3001:3001
  #   depends_on:
  #     - tor
  #   volumes:
  #     - ./uptimekuma/data:/app/data:rw
  #   networks:
  #     - nginx
  # tor:
  #   build: ./tor
  #   restart: always
  #   environment:
  #     PUBLIC_PORT: 5100
  #     TOR_SITE: satstraoq35jffvkgpfoqld32nzw2siuvowanruindbfojowpwsjdgad.onion
  #     TOR_SITE_PORT: 80
  #   ports:
  #     - 5100:5100
  #     - 9001:9001
  #     - 9050:9050
  #   networks:
  #     - nginx
networks:
  nginx:
    driver: bridge
    external: true
