export const onionUrl = 'http://satstraoq35jffvkgpfoqld32nzw2siuvowanruindbfojowpwsjdgad.onion'
export const onionUrlTest = 'http://testraliar7xkhos2gipv2k65obykofb4jqzl5l4danfryacifi4t7qd.onion'
export const unsafeUrl = 'https://unsafe.satstralia.com/'
export const learnUrl = 'https://learn.robosats.com/'
export const email = 'info@satstralia.com'
export const nostrPubKey = 'npub1z94lxjf7m5snda0qc6s3kmpy6r4nfw74h78da9j6j4y8ym08zrrs459wpr'